version: 2

models:
  - name: doctor_summary
    description: "Aggregated summary showing each doctor's unique patient count and top diagnosis"
    columns:
      - name: doctor_name
        description: "Name of the doctor"
        tests:
          - not_null
      - name: unique_patients
        description: "Number of unique patients the doctor has seen"
        tests:
          - not_null
      - name: top_diagnosis
        description: "The most frequent diagnosis made by the doctor"
        tests:
          - not_null
